name: Release Workflow

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      tags:
        description: 'Version Tag'
        required: true


permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: 'go.mod'
    - name: Load secrets from 1Password
      id: op-load-secrets-env
      uses: 1password/load-secrets-action@v2
      with:
        export-env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        GPG_PRIVATE_KEY: 'op://CI/zvdciazdapcpu7ly2d44e5bqaa/private_key'
        GPG_PASSPHRASE: 'op://CI/zvdciazdapcpu7ly2d44e5bqaa/password'
        GITHUB_TOKEN: ''
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
      with:
        gpg_private_key: ${{ steps.op-load-secrets.outputs.GPG_PRIVATE_KEY }}
        passphrase: ${{ steps.op-load-secrets.outputs.GPG_PASSPHRASE }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
    - uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
      with:
        subject-path: 'dist/checksums.txt'
